### ISSUE TITLE
Add more to the README.md (don't mean to be rude)

### ISSUE THREAD

**Issue by AdrianKoshka** [Epse/EpPos#13]
Saw this project posted to [/r/coolgithubprojects](https://www.reddit.com/r/coolgithubprojects). Currently your README is **very** lacking, which will make people just ignore your project. 

some things I suggest to add to the README are

- depends.
- one or more screenshot(s) of the software running.
- list of author(s).
- what license it's under.
- what the software does (for people who might not be familiar w/ POS).

not trying to be annoying, just don't want your effort to go to waste!

**Comment by Epse** [comment]
Yes you ate absolutely right. I just didn't put that as a priority on my to do list.
