### ISSUE TITLE
Cash Object & Order

### ISSUE THREAD

**Issue by stopplay** [Epse/EpPos#20]
Great Work!

Cash Objects : 
It's great you are able to capture the total value of the products paid for. 
However I advice that you will need to be able to view Transactions, This would include the timestamp and items sold, total cost.

Order : 

The current order shows the Product Name only, will be great to include the product Price, just so the customer knows what they paid for.
This would link with the new Transactions class, where you are able in future to link to a printer for receipt.

**Comment by Epse** [comment]
I'm closing this issue and referencing this to #21 which is baically tracking the same functionality, just without having to create yet another class that essentially isn't necessary and mostly confusing.

Thanks for the appreciation stil!!
