### ISSUE TITLE
Allow deleting a specific item in the ranking

### ISSUE THREAD

**Issue by spaetz** [Epse/EpPos#35]
If I add
```
Burger
Coke
Burger
```
and I want to delete the last Burger because some guest canceled the order, I would like to be able to have the item disappear where I clicked the "X". Right now we search for the product name and delete a random one.

**Comment by Epse** [comment]
That would probably be doable, albeit with a change in the Order model.
Any reason why you might want that? I had considered it, but concluded that if there is any difference between say, two `Burger`'s on an order, these two should really be separate products.

**Comment by spaetz** [comment]
Consider an order list in which people around a table in a restaurant order things. If somebody cancels an item you want to delete the item which is next to the other items of that person on the list.

Am 22. Oktober 2017 10:59:34 MESZ schrieb Stef Pletinck <notifications@github.com>:
>That would probably be doable, albeit with a change in the Order model.
>Any reason why you might want that? I had considered it, but concluded
>that if there is any difference between say, two `Burger`'s on an
>order, these two should really be separate products.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Epse/EpPos/issues/35#issuecomment-338462158

-- 
Sent from mobile device. Please excuse brevity and tpyos.
