### ISSUE TITLE
ValueError: too many values to unpack (expected 2) on reset_order() [line 181, pos/views.py]

### ISSUE THREAD

**Issue by manuelfedele** [Epse/EpPos#46]
helper.setup_handling(request) returns 3 value tuple.
This raises the ValueError exception (python3.6.4) on line 181 of pos/views.py.
Just by adding an underscore for currency unpacking (there's no need to save currency value in reset order) the bug is fixed.
**from**
`cash, current_order = helper.setup_handling(request)`
**to**
`cash, current_order, _ = helper.setup_handling(request)`

**Comment by Epse** [comment]
Fixed in #49 
Protip, add a "fixed #49" message in your commit text somewhere to make this easier.
Thanks!
