### ISSUE TITLE
Make it work! [Clear Order Button]

### ISSUE THREAD

**Issue by manuelfedele** [Epse/EpPos#47]
By adding
`Order_Item.objects.filter(order=current_order).delete()`
in pos/views.py, after line 181, in reset_order() method, Clear Order button works for real, deleting **Item_Order** objects of associated **Order** object.

**Comment by Epse** [comment]
OH. Well f***k. How in the flippin heck did I not think of deleting the `Item_Order` objects...
Thanks I'll look at your pulls

**Comment by Epse** [comment]
Fixed in #49

**Comment by manuelfedele** [comment]
Just one thing I noticed later. When an order is cleared, the reset method should look if "stock applies" and refund items. Just like when you remove a single product from anche order. I have the code fix in my laptop bit I'm texting from another PC now. Cya! :)

**Comment by Epse** [comment]
Blimey the overseights on my end just keep coming....
