### ISSUE TITLE
Colours for products

### ISSUE THREAD

**Issue by Epse** [Epse/EpPos#64]
Products in a POS system are often colour-coded.
We want to add a colour property to the `Product` model, a dropdown to select a colour in the admin, order the products in the `Order` screen by colour and show the colours.

**Comment by ZeroCoolHacker** [comment]
What is the range of colors? Simple more common colors or do you want the full spectrum?
Like you use in a paint store where they give you a shade card with variety of color shades.
Or just simple red blue green etc
