### ISSUE TITLE
Having an issue where from my mobile phone, order invoice is being generated with no products

### ISSUE THREAD

**Issue by dnk8n** [Epse/EpPos#77]
Only on my phone, which is an Android running Chrome.

Potentially something in the javascript is not compatible? I need help knowing how to give back the relevant debug information.

I have an instance running live at the moment, I can give credentials out if you want them. My twitter handle is the same as my github, so if you want, you can DM me and I will provide credentials.

**Comment by Epse** [comment]
I've just tried using android on my phone, and I can't reproduce. Javascript debugging from a phone is a mild pain, I'll get back to you

10 May 2019, 18:42 by notifications@github.com:

**Comment by Epse** [comment]
Is this in the admin interface, or after completing an order?

**Comment by dnk8n** [comment]
Oh sorry, this is after completing an order. Printing directly from after tapping cash or card payment menu button.

**Comment by Epse** [comment]
Huh, I'll have a look. I can't see any way that could go wrong, as that page has basically no javascript (just a little to trigger the printer dialog) 

11 May 2019, 18:18 by notifications@github.com:

**Comment by Epse** [comment]
Yeah I can confirm this... weird

**Comment by Epse** [comment]
This bug never happens when I connect the devtools to my phone to inspect what happens...

**Comment by Epse** [comment]
This appears to be a speed and javascript JIT bug, according to code the following should happen:

1. An alert is shown to ask if you want to print the ticket
2. Depending on the response, the ticket is shown in a new tab or not
3. The page sends a request to the server, indicating payment
4. The current order is cleared by the server

Apparently Chrome on mobile, after clicking 'yes', first sends the request asking to clear the order before loading the new tab. This should probably be changed

**Comment by dnk8n** [comment]
Very glad that this bug was at least reproducible to more than just my phone!

If I can do anything to help, please ask and I will jump in as soon as I can.

**Comment by Epse** [comment]
No worries, it's just a symptom of some not-so-great design decisions on the back end.
The new frontend should basically fix that, if you want to try it (probably best not to do this in the store), you can download the development version [here](https://github.com/Epse/EpPos/tree/79-better-frontend).

**Comment by dnk8n** [comment]
I am guessing to upgrade to this version I,

`git checkout 79-better-frontend`
`docker-compose up -d --build`

**Comment by dnk8n** [comment]
I worked out I needed to `docker volume rm eppos_static` and then `docker-compose up -d` in order to get the front-end looking as intended.

**Comment by dnk8n** [comment]
Can confirm that the receipt now displays on my mobile phone!

**Comment by dnk8n** [comment]
Out of curiosity. Do invoices normally show the amount received, etc? Just noticed the feature that calculates change too.

**Comment by Epse** [comment]
They don't, I've kept the issue open so that I can eventually add that. The change calculator is entirely client side 

15 May 2019, 07:55 by notifications@github.com:
