### ISSUE TITLE
docker-compose run web ./manage.py createsuperuser "No such file or directory"

### ISSUE THREAD

**Issue by nateesh** [Epse/EpPos#88]
Hello

docker-compose up seems to have worked fine. There was no `db` folder in `web` folder so I added one before running docker-compose up.

docker-compose run is yielding the following :
`/usr/bin/env: ‘python3\r’: No such file or directory`

which I understand is probably super simple to solve, but I am noob and stumped looking through stackExchange etc...

tia

**Comment by Epse** [comment]
That looks like an issue with the newlines. What OS are you running?

The `\r` you are seeing is part of how Windows encodes a new line, using `\r\n`, whereas Linux, MacOS and other Unix-likes only use `\n` and might get confused by a stray `\r`

**Comment by nateesh** [comment]
Hey I'm on windows, did not figure it out however it's a good starting point. Thank you so much for your response I'll look into it when I have some spare time :)
